### ISSUE TITLE
Release request: Do not assume specific order of headers

### ISSUE THREAD

**Issue by m-uppet** [nachomazzara/parse-multipart-data#12]
I used this library successfully with the following PR https://github.com/nachomazzara/parse-multipart-data/pull/9

Would it be possible to add this PR to a release as soon as possible, as this isn't included in 1.4.0 ?

**Comment by nachomazzara** [comment]
hey! thanks for the heads up. [1.5.0 released](https://www.npmjs.com/package/parse-multipart-data)

**Comment by m-uppet** [comment]
No problem, thanks a bunch !
