### ISSUE TITLE
License attribution for partial implementation in unjs/h3

### ISSUE THREAD

**Issue by pi0** [nachomazzara/parse-multipart-data#17]
Hi dear @nachomazzara. Thanks for your work on this project 💯 

Recently, we used part of your code to implement multipart data utils for [unjs/h3](https://github.com/unjs/h3). H3 itself is MIT licensed and your name in addition to base fork licenses are linked [here](https://github.com/unjs/h3/blob/main/src/utils/multipart.ts).

Please let me know if you like it to be written differently in there otherwise feel free to close issue. Cheers!

Linking https://github.com/freesoftwarefactory/parse-multipart/issues/35

**Comment by nachomazzara** [comment]
Thanks :) Everything good.
